### ISSUE TITLE
Add Config file to Container

### ISSUE THREAD

**Issue by KarolChlasta** [KarolChlasta/nsp-code#44]
Np. setupCloud.sh

--provider AWS
--secretKey
--accesskey

**Comment by psochaczewski** [comment]
Zrobione

do konfiguracji NSP służy plik  nsp-code\config.txt i jest ładowany przy starcie kontenera.
nsp_aws_access_key_id=XXXXXXXXX
nsp_aws_secret_access_key=YYYYYYYYY
nsp_region=eu-west-1
nsp_debug=0
nsp_scientist_name=unknown
nsp_scientist_surname=unknown
nsp_scientist_email=unknown@unknown.com
nsp_project_info=unknown
